version: '3.2'

services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    container_name: metadata_php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app:delegated
    ports:
      - 23078:80
    links:
      - mariadb
    # environment:
    #   - COMPOSE_CONVERT_WINDOWS_PATHS=1

  mariadb:
    image: mariadb:10.3
    container_name: metadata_mariadb
    volumes:
      # - ./docker/dbdata:/var/lib/mysql
      - apps_persistent:/var/lib/mysql
    ports:
      - 23076:3306
    restart: always
    environment:
      - TZ=Asia/Jakarta
      # - MYSQL_USER=apps_data
      # - MYSQL_PASSWORD=pass_apps_data
      - MYSQL_ROOT_PASSWORD=admin_db
      - MYSQL_DATABASE=apps_db

volumes:
  apps_persistent:
